#Reference: https://blog.csdn.net/forezp/article/details/85081162
server:
  port: 8083
spring:
  cloud:
    gateway:
      routes:
        - id: limit-route
          uri: http://httpbin.org:80/get
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
          #Spring Cloud Gateway限流器，基于令牌桶算法
          filters:
            - name: RequestRateLimiter
              args:
                #用于限流的解析器的Bean对象的名字。它使用SpEL表达式根据#{@beanName}从Spring容器中获取Bean对象
                key-resolver: '#{@hostAddrKeyResolver}'
                #令牌桶每秒填充平均速率
                redis-rate-limiter.replenishRate: 1
                #令牌桶总容量
                redis-rate-limiter.burstCapacity: 3
  application:
    name: gateway-request-rate-limiter
  redis:
    host: localhost
    port: 6379
    database: 0