#Reference: https://blog.csdn.net/forezp/article/details/84926662
server:
  port: 8081
spring:
  profiles:
    active: after-route
#After Route Predicate Factory
---
spring:
  cloud:
    gateway:
      routes:
        - id: after-route
          uri: http://httpbin.org:80/get
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
  profiles: after-route
#Header Route Predicate Factory
---
spring:
  cloud:
    gateway:
      routes:
        - id: header-route
          uri: http://httpbin.org:80/get
          predicates:
            - Header=X-Request-Id, \d+
  profiles: header-route
#Cookie Route Predicate Factory
---
spring:
  cloud:
    gateway:
      routes:
        - id: cookie-route
          uri: http://httpbin.org:80/get
          predicates:
            - Cookie=name, forezp
  profiles: cookie-route
#Host Route Predicate Factory
---
spring:
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: http://httpbin.org:80/get
          predicates:
            - Host=**.fangzhipeng.com
  profiles: host_route
#Method Route Predicate Factory
---
spring:
  cloud:
    gateway:
      routes:
        - id: method_route
          uri: http://httpbin.org:80/get
          predicates:
            - Method=GET
  profiles: method_route
#Path Route Predicate Factory
---
spring:
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://httpbin.org:80/get
          predicates:
            - Path=/foo/{segment}
  profiles: path_route
#Query Route Predicate Factory